application: releasenotesgenerator
version: 9
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: main.app



libraries:
- name: django
  version: "1.4"

- name: ssl
  version: latest